MolSSI-BSE/basis_set_exchange

basis_set_exchange/converters/dalton.py

Replace duplicate line containing element name and contraction string with line containing atomic number

Adjust Dalton converter

---

basis_set_exchange/api.py
basis_set_exchange/converters/bdf.py
basis_set_exchange/converters/convert.py

Adds the BDF format converter
Combines and Supercedes #86 #85 #84 
@AndyC743 Does this look reasonable?

Adds the BDF format converter

---

basis_set_exchange/writers/gamess_us.py

Adds a blank line before $END in GAMESS-US

Add blank line before  for GAMESS-US

---

.github/workflows/CI.yml
basis_set_exchange/validator.py

Add testing for Windows & Mac
Also fixes #137

Add Windows & macos to CI

---

basis_set_exchange/cli/bsecurate_cli.py
basis_set_exchange/tests/common_testvars.py
basis_set_exchange/tests/test_cli.py
basis_set_exchange/tests/test_curatecli.py

Fix cli tests

---

basis_set_exchange/readers/nwchem.py
basis_set_exchange/writers/nwchem.py
doc/augmentation.rst
doc/usage.rst

NWChem angular momentum fixes

---

basis_set_exchange/data/dunning/cc-pV6Z.1.json

Add missing reference for sulfur in cc-pV6Z.

---

.github/workflows/CI.yml
basis_set_exchange/readers/helpers.py
basis_set_exchange/readers/libmol.py
basis_set_exchange/readers/molpro.py
basis_set_exchange/readers/read.py
basis_set_exchange/writers/common.py
basis_set_exchange/writers/libmol.py
basis_set_exchange/writers/write.py
setup.py

Features:
Molpro user input reader
Molpro system library reader
Molpro system library writer
The problem is that there's scant documentation on the formats (especially the user input for ECPs) in the manual.
Closes #115.

Implement Molpro readers and writer

---

.gitignore
basis_set_exchange/tests/common_testvars.py
basis_set_exchange/tests/test_api.py
basis_set_exchange/tests/test_writers.py
basis_set_exchange/writers/fhiaims.py
basis_set_exchange/writers/write.py

By request of FHI-aims users on FHI-aims Slack.

Implement FHI-aims output type

---

.github/workflows/CI.yml
basis_set_exchange/__init__.py
basis_set_exchange/cli/bse_handlers.py
basis_set_exchange/readers/g94.py
basis_set_exchange/writers/fhiaims.py
setup.py

Some small cleanup before release
* Yapf on all files
* Clean up dependencies in setup.py/GHA

Slight cleanup before release

---

basis_set_exchange/writers/qchem.py

Correct auxiliary basis output for Q-Chem

---

.github/workflows/CI.yml
basis_set_exchange/cli/bse_handlers.py
basis_set_exchange/convert.py
basis_set_exchange/memo.py
basis_set_exchange/writers/jaguar.py

Cleanup code via yapf and update codecov GHA

Cleanup & Fix GHA

---

basis_set_exchange/readers/cp2k.py
basis_set_exchange/readers/read.py

Closes #107 
Closes #173 
This is dependent on #165; I'll rewrite the history once #165 has been merged

Cp2k reader

---

basis_set_exchange/writers/bdf.py

Previous BSE releases cannot correctly output basis thats with ECP (such as def2-SVP) to BDF format, this fix it.

Fix BDF formatting issue with ECP basis

---

basis_set_exchange/readers/libmol.py

This function is no more located in helpers but in manip

Fix create_element_data

---

basis_set_exchange/data/REFERENCES.json
basis_set_exchange/data/sigmaNZ/sigmaDZHF.1.json
basis_set_exchange/data/sigmaNZ/sigmaSZHF.1.json
basis_set_exchange/data/sigmaNZ/sigmaTZHF.1.json

The paper describing the sigmaNZHF basis sets is now online.

Update reference for sigmaNZHF basis sets

---

.github/workflows/build_docs.yml
.github/workflows/codeql.yml
.github/workflows/tests.yml
basis_set_exchange/bundle.py
basis_set_exchange/tests/test_bundle.py
versioneer.py

Enable tests for python 3.12 and fix any compatibility issues

Python 3.12 compatibility

---

.github/workflows/tests.yml

Enable testing against python 3.13

---

CHANGELOG

See the updated [Changelog](https://github.com/MolSSI-BSE/basis_set_exchange/blob/rel11/CHANGELOG) for details!

Release v0.11

---

basis_set_exchange/data/6-311xxG(d,p).metadata.json
basis_set_exchange/data/METADATA.json

Hi! I know this is a tiny little thing, but I was working with the API, and this error made it difficult to process something that I needed. Let me know if I made any mistakes.

Fixing zorilla -> zorrilla

---

basis_set_exchange/readers/bsejson.py
basis_set_exchange/readers/read.py

Implement json read-in format.
