README.md, basis_set_exchange/bundle.py, doc/conf.py, doc/index.rst, doc/project_doc.rst, versioneer.py
- replace bse.pnl.gov/bse/portal with www.basissetexchange.org
- use https if possible
- note: http://www.ipc.uni-karlsruhe.de/tch/tch1/index.html is dead
=> Update URLs [skip ci]

setup.py
The current pip resolver still pulls in `importlib_metadata` 3.0 even though it is restricted by argcomplete. So force the package constraint at the top.
This should be revisited when either the constraint is lifted on argcomplete, or the pip resolver gains some semblance of sanity.
=> Force importlib_metadata < 3

basis_set_exchange/api.py
If only a subset of elements is requested, the list of used functions needs to be updated.
This is a partial fix to #158.
=> Update list of used function types in get_basis

basis_set_exchange/writers/molpro.py, basis_set_exchange/writers/write.py
Molpro output didn't specify angular momentum type, which leads to wrong results.
Also, the Psi4 check was in the wrong order IMHO, since it lead to e.g. 6-31G** given in spherical form #158. Switching around the check to prefer cartesian form fixes that issue.
=> Specify angular momentum type in Molpro output

basis_set_exchange/ints.py, basis_set_exchange/sort.py, doc/usage.rst
At present, the sorting algorithm isn't placing the steepest functions at first, see #140. This issue can be avoided by moving to a more physically motivated sorting algorithm, i.e., by sorting with respect to the radial extent of the basis function measured with the <r^2> expectation value.
The idea is to sort
- all exponents in decreasing value, i.e. tightest to the most diffuse
- all contractions from tightest to most diffuse
This just requires the use of some one-center integrals. I've implemented the equations for GTOs, but STOs and numerical basis functions could also be handled in an analogous manner.
For example, the P shell in the 6-31G* basis for Fe in NWChem format looks at present as
```
Fe    P
0.1259980000E+04       0.4028018665E-02       0.00000000             0.00000000 …
```
=> Improve sorting algorithm

basis_set_exchange/manip.py
This PR runs `prune_basis` in `make_general`, which eliminates any duplicate exponents from the basis set. This is important for conversion of basis sets, since reading in a basis in a segmented format otherwise leads to duplication of exponents in several basis set output formats.
Closes #166
=> Prune basis in make_general to avoid duplicate exponents (#166)

basis_set_exchange/readers/read.py, basis_set_exchange/readers/ricdlib.py, basis_set_exchange/writers/molcas.py, basis_set_exchange/writers/ricdwrap.py, basis_set_exchange/writers/write.py
This PR implements a reader for the RICDLib format used in OpenMolcas for storing automatically generated Cholesky auxiliary basis sets.
I've also included an output format i.e. writer to generate suitable input for OpenMolcas to generate the RICDLib file (wrapricd).
To use the code, one just has to
1. `bse get-basis ... ricdwrap > basis.input` to generate the OpenMolcas input
2. run OpenMolcas with `pymolcas basis.input` to generate the RICDLib file and
3. extract the acCD basis with `bse convert-basis basis.RICDLib ...`
Also fixes #218 i.e. the lack of discrimination between spherical and cartesian functions
=> Implement reader and interface for MolCAS RICDLib format

basis_set_exchange/writers/g94.py, basis_set_exchange/writers/write.py, doc/usage.rst
The current Gaussian'94 format causes Gaussian to crash if the basis set has elements that are not included in the calculation.
This PR adds a new output format that adds the `-` sign in front of the element symbols, so that Gaussian runs smoothly even if you don't have some elements present.
=> Add Gaussian system library format output

basis_set_exchange/api.py, basis_set_exchange/cli/bse_cli.py, basis_set_exchange/cli/bse_handlers.py, basis_set_exchange/ints.py, basis_set_exchange/lut.py, basis_set_exchange/manip.py, basis_set_exchange/readers/dalton.py, basis_set_exchange/readers/demon2k.py, basis_set_exchange/readers/g94.py, basis_set_exchange/readers/gbasis.py, basis_set_exchange/readers/genbas.py, basis_set_exchange/readers/helpers.py, basis_set_exchange/readers/molcas.py, basis_set_exchange/readers/nwchem.py, basis_set_exchange/readers/turbomole.py
AutoAux, a method for generation of general-use auxiliary basis sets, has been described in [J. Chem. Theory Comput. 13, 554 (2017)](https://doi.org/10.1021/acs.jctc.6b01041). I've verified with help from Frank Neese and Georgi Stoychev that this implementation reproduces ORCA for the cc-pwCVQZ basis set at least for B, C, N, and O, and doing so found three typos in the paper.
auto-ABS, a method for Coulomb-fitting auxiliary basis sets, has been described in [J. Chem. Phys. 127, 074102 (2007)](https://doi.org/10.1063/1.2752807). This scheme is much sim
=> Implement AutoAux and auto-ABS methods for automatic formation of auxiliary basis sets

basis_set_exchange/data/6-311GSS-RIFIT.1.table.json, basis_set_exchange/data/6-311GSS-RIFIT.metadata.json, basis_set_exchange/data/6-311GSS.metadata.json, basis_set_exchange/data/6-31GSS-RIFIT.1.table.json, basis_set_exchange/data/6-31GSS-RIFIT.metadata.json, basis_set_exchange/data/6-31GSS.metadata.json, basis_set_exchange/data/METADATA.json, basis_set_exchange/data/REFERENCES.json, basis_set_exchange/data/pople/6-311GSS-RIFIT.1.element.json, basis_set_exchange/data/pople/6-311GSS-RIFIT.1.json, basis_set_exchange/data/pople/6-31GSS-RIFIT.1.element.json, basis_set_exchange/data/pople/6-31GSS-RIFIT.1.json
Described in [J. Comput. Chem. 34, 2568 (2013)](http://doi.org/10.1002/jcc.23430)
=> Include RIMP2 sets for 6-31G** and 6-311G** basis sets.

basis_set_exchange/bundle.py, basis_set_exchange/writers/write.py
When creating bundles, skip any basis sets for which a particular format does not support a function type
Ie, fhiaims and any basis set with ECP. But this is a general solution (I hope)
=> Skip creating bundle files for incompatible basis set/writer combos

setup.py
Relax restrictive constraint on importlib version that caused conflicts
with software in the Jupyter ecosystem.
P.S. You've configured CI to only run on pushes & pull requests to `master`.
When following a regular branching strategy, I believe this means that CI will not run on forks (?), which prevents contributors from checking whether CI passes before making a pull request.
Furthermore, with the new policies you'll now need to approve workflow runs manually.
I suggest you enable CI to run on any branch.
On my fork, I've now pushed to `master` in order to get the workflow to run
=> fix: importlib constraint

basis_set_exchange/data/METADATA.json, basis_set_exchange/data/REFERENCES.json, basis_set_exchange/data/cadpac-tz2p.1.table.json, basis_set_exchange/data/cadpac-tz2p.metadata.json, basis_set_exchange/data/dunning_hay/cadpac-tz2p.1.element.json, basis_set_exchange/data/dunning_hay/cadpac-tz2p.1.json
These come from the CADPAC basis set file I got from Aron Cohen, and are
* 3S2P for H
* 4S2P for Li
* 5S4P2D for B-Ne
* 9S6P3D for Si-Cl
Cartesian basis functions are used.
For the first-row elements, the composition matches with the one given in [J. Chem. Phys. 108, 2545 (1998)](https://doi.org/10.1063/1.475638). The second-row composition was given by Aron, but it is also the only "custom" basis set in the CADPAC file that has these atoms with polarization functions.
=> Include CADPAC TZ2P basis set.

basis_set_exchange/cli/bse_cli.py, basis_set_exchange/cli/bse_handlers.py, basis_set_exchange/convert.py
When converting from a segmented contraction basis set format to a general contraction basis set format like NWChem, one needs to be able to run make_general in the conversion.
=> Add make-gen argument to convert-basis

.github/workflows/tests.yml
Python 3.6 is not available on the ubuntu-latest runner anymore. This PR changes the test to use Python 3.11
=> Update python test from 3.6 to 3.11

basis_set_exchange/writers/dalton.py
This PR adjusts ECP writing to the Dalton format.
An example of the format is:
```
$
a  37
$
3  28
1
2      3.843114000000    -12.316900000000
3
2      5.036551000000     89.500198000000
2      1.970849000000      0.493761000000
2      3.843114000000     12.316900000000
3
2      4.258341000000     58.568974000000
2      1.470709000000      0.431791000000
2      3.843114000000     12.316900000000
3
2      3.023127000000     26.224898000000
2      0.650383000000      0.962839000000
2      3.843114000000     12.316900000000
$
```
A full file is available here: https://gitlab.com/dalton/dalton/-/raw/30e11f9d007e39fc617d5fc37806cba08dcfb277/basis/ecp_data/def2_svp?inline=true 
Note that Dalton keeps regular basis sets and basis sets in different files (`basis` and `basis/ecp_data`).
=> Adjust dalton ECP writing

basis_set_exchange/readers/ricdlib.py
create_element_data and function_type_from_am have been moved and these changes are needed to make the RICDLib reader work again.
=> Fix issues in RICDLib reader related to moving of code

basis_set_exchange/data/REFERENCES.json
Many journals failed to include the subtitle in their automated DOI entries. This adds the missing subtitles to the ANO papers by Widmark and coworkers.
=> ANO basis set references were missing the subtitles

basis_set_exchange/ints.py, basis_set_exchange/readers/ricdlib.py
One regular expression was missing the `r` prefix, and some equations in `ints.py` weren't properly escaped.
Hopefully fixes issue #294
=> Fix docstring and other escape sequence issues

basis_set_exchange/data/METADATA.json, basis_set_exchange/data/REFERENCES.json, basis_set_exchange/data/epc-8s8p8d.1.table.json, basis_set_exchange/data/epc-8s8p8d.metadata.json, basis_set_exchange/data/pb/epc-8s8p8d.1.element.json, basis_set_exchange/data/pb/epc-8s8p8d.1.json
Implements even-tempered 8s8p8d protonic orbital basis set from [J. Chem. Phys. 147, 114113 (2017)](https://doi.org/10.1063/1.4996038)
=> Implement even-tempered 8s8p8d protonic basis

basis_set_exchange/writers/write.py
Gaussian doesn't seem tolerant of blank lines after the commented header and the start of the basis set for the system library format. So this puts in a hack to remove those lines.
Fixes #313
=> Fix blank lines in gaussian system format

.github/workflows/build_docs.yml, .github/workflows/codeql.yml, .github/workflows/tests.yml
Upgrades the versions of various github actions (setup-python and CodeQL). Hopefully, this will fix some of the errors on macos runners.
Removing the `shell` from the workflow seems to have fixed it. It doesn't seem to be required, and it seems part of the bug causing failing tests: https://github.com/actions/setup-python/issues/942
=> Upgrade versions in GHAs

basis_set_exchange/data/REFERENCES.json
The author order was incorrect compared to the actual paper, [doi:10.1007/s00214-003-0537-0](https://doi.org/10.1007/s00214-003-0537-0).
=> Fix author order in roos2004a reference.
